# Generated by Django 4.2 on 2023-04-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pics',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_type',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Parent', 'Parent')], default='Student', max_length=10),
        ),
    ]
