# Generated by Django 4.2 on 2023-04-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_userprofileinfo_profile_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pics',
            field=models.ImageField(blank=True, upload_to='media/profile_images/', verbose_name='profile picture'),
        ),
    ]
